package com.droidmind.feature.chat.data.remote.dto

import kotlinx.serialization.Serializable

/**
 * Request body for Gemini's `generateContent` endpoint.
 *
 * Mirrors Gemini's exact expected JSON shape — this is intentionally NOT
 * the same as our domain [com.droidmind.feature.chat.domain.model.Message],
 * since the API's request shape and our domain model can evolve
 * independently. A mapper converts between them.
 *
 * @param contents the conversation content to send to the model.
 */
@Serializable
data class GeminiRequest(
    val contents: List<GeminiContent>
)

/**
 * A single content entry within a Gemini request or response — a container
 * for one or more [GeminiPart]s, representing what one participant said.
 *
 * @param parts the pieces of content (currently just text) in this entry.
 */
@Serializable
data class GeminiContent(
    val parts: List<GeminiPart>
)

/**
 * A single piece of content — for now, just text. Gemini's real API
 * supports other part types (images, etc.) which we'll add when we build
 * the Camera AI feature later.
 *
 * @param text the text content of this part.
 */
@Serializable
data class GeminiPart(
    val text: String
)

/**
 * Top-level response body from Gemini's `generateContent` endpoint.
 *
 * @param candidates the possible responses generated by the model —
 * we'll use the first one.
 */
@Serializable
data class GeminiResponse(
    val candidates: List<GeminiCandidate>
)

/**
 * A single candidate response from the model.
 *
 * @param content the generated content for this candidate.
 */
@Serializable
data class GeminiCandidate(
    val content: GeminiContent
)