package com.droidmind.feature.chat.domain.model

import java.util.UUID

/**
 * Represents a single message in a chat conversation, from either the user
 * or the AI assistant.
 *
 * This is a pure domain model — it has no knowledge of how it was created
 * (e.g. from a Retrofit DTO) or how it will be displayed (e.g. as a Compose
 * UI element). Both the data layer and presentation layer convert to/from
 * this type via mappers, keeping this class stable even if the API response
 * shape or UI representation changes.
 *
 * @param id a unique identifier for this message, used for list diffing
 * (e.g. in Compose's `LazyColumn`) and as a database primary key later.
 * @param content the text content of the message.
 * @param sender who sent this message — the user or the AI.
 * @param timestamp when this message was created, in epoch milliseconds.
 */
data class Message(
    val id: String = UUID.randomUUID().toString(),
    val content: String,
    val sender: Sender,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Identifies who sent a given [Message].
 */
enum class Sender {
    /** The message was typed or spoken by the human user. */
    USER,

    /** The message was generated by an AI model (OpenAI, Gemini, Claude, etc.). */
    AI
}